name: r0_app
description: A Flutter app for recording and reporting workflow reports, truck, heavy vehicle, and factory reports.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  sqflite: ^2.3.0
  path: ^1.8.3
  intl: ^0.20.2
  google_maps_flutter: ^2.5.0
  shared_preferences: ^2.2.2
  shared_preferences_android: ^2.2.2
  shared_preferences_ios: ^2.1.1
  shared_preferences_linux: ^2.2.2
  shared_preferences_web: ^2.2.2
  shared_preferences_windows: ^2.2.2
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  generate: true  # For internationalization

  assets:
    - assets/translations/
    - assets/images/ 