org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8
org.gradle.workers.max=4
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.configureondemand=true
android.useAndroidX=true
android.enableJetifier=true
org.gradle.java.home=C:/Program Files/Microsoft/jdk-17.0.17.10-hotspot
kotlin.incremental=false
