// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4jwGwxDDQW83Y4CuRV7-lXxqYI-21EUc',
    appId: '1:863567983944:web:527491e3670545df2b6f7d',
    messagingSenderId: '863567983944',
    projectId: 'r0v01-5b577',
    authDomain: 'r0v01-5b577.firebaseapp.com',
    storageBucket: 'r0v01-5b577.firebasestorage.app',
    measurementId: 'G-TQKLTDJRCQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByWq1RG_W4HdqJv_jxolnat3ao98F3Www',
    appId: '1:863567983944:android:5508e5a1b74accdb2b6f7d',
    messagingSenderId: '863567983944',
    projectId: 'r0v01-5b577',
    storageBucket: 'r0v01-5b577.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9iI3tEXouvO0yPBv4r_ECGdOCLG9aTfM',
    appId: '1:863567983944:ios:8471d24121a1877a2b6f7d',
    messagingSenderId: '863567983944',
    projectId: 'r0v01-5b577',
    storageBucket: 'r0v01-5b577.firebasestorage.app',
    iosBundleId: 'com.example.r0App',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9iI3tEXouvO0yPBv4r_ECGdOCLG9aTfM',
    appId: '1:863567983944:ios:8471d24121a1877a2b6f7d',
    messagingSenderId: '863567983944',
    projectId: 'r0v01-5b577',
    storageBucket: 'r0v01-5b577.firebasestorage.app',
    iosBundleId: 'com.example.R0',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4jwGwxDDQW83Y4CuRV7-lXxqYI-21EUc',
    appId: '1:863567983944:web:527491e3670545df2b6f7d',
    messagingSenderId: '863567983944',
    projectId: 'r0v01-5b577',
    authDomain: 'r0v01-5b577.firebaseapp.com',
    storageBucket: 'r0v01-5b577.firebasestorage.app',
    measurementId: 'G-TQKLTDJRCQ',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyB4jwGwxDDQW83Y4CuRV7-lXxqYI-21EUc',
    appId: '1:863567983944:web:527491e3670545df2b6f7d',
    messagingSenderId: '863567983944',
    projectId: 'r0v01-5b577',
    authDomain: 'r0v01-5b577.firebaseapp.com',
    storageBucket: 'r0v01-5b577.firebasestorage.app',
    measurementId: 'G-TQKLTDJRCQ',
  );

} 