// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static const _webApiKey = String.fromEnvironment('FIREBASE_WEB_API_KEY');
  static const _webAppId = String.fromEnvironment('FIREBASE_WEB_APP_ID');
  static const _androidApiKey =
      String.fromEnvironment('FIREBASE_ANDROID_API_KEY');
  static const _androidAppId =
      String.fromEnvironment('FIREBASE_ANDROID_APP_ID');
  static const _iosApiKey = String.fromEnvironment('FIREBASE_IOS_API_KEY');
  static const _iosAppId = String.fromEnvironment('FIREBASE_IOS_APP_ID');
  static const _messagingSenderId =
      String.fromEnvironment('FIREBASE_MESSAGING_SENDER_ID');
  static const _projectId = String.fromEnvironment('FIREBASE_PROJECT_ID');
  static const _authDomain = String.fromEnvironment('FIREBASE_AUTH_DOMAIN');
  static const _storageBucket =
      String.fromEnvironment('FIREBASE_STORAGE_BUCKET');
  static const _measurementId =
      String.fromEnvironment('FIREBASE_MEASUREMENT_ID');
  static const _iosBundleId = String.fromEnvironment('FIREBASE_IOS_BUNDLE_ID');
  static const _macosBundleId =
      String.fromEnvironment('FIREBASE_MACOS_BUNDLE_ID');

  static String _value(String dartDefineValue, String dotenvKey) {
    if (dartDefineValue.isNotEmpty) {
      return dartDefineValue;
    }
    try {
      return dotenv.env[dotenvKey] ?? '';
    } catch (_) {
      return '';
    }
  }

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
        apiKey: _value(_webApiKey, 'FIREBASE_WEB_API_KEY'),
        appId: _value(_webAppId, 'FIREBASE_WEB_APP_ID'),
        messagingSenderId:
            _value(_messagingSenderId, 'FIREBASE_MESSAGING_SENDER_ID'),
        projectId: _value(_projectId, 'FIREBASE_PROJECT_ID'),
        authDomain: _value(_authDomain, 'FIREBASE_AUTH_DOMAIN'),
        storageBucket: _value(_storageBucket, 'FIREBASE_STORAGE_BUCKET'),
        measurementId: _value(_measurementId, 'FIREBASE_MEASUREMENT_ID'),
      );

  static FirebaseOptions get android => FirebaseOptions(
        apiKey: _value(_androidApiKey, 'FIREBASE_ANDROID_API_KEY'),
        appId: _value(_androidAppId, 'FIREBASE_ANDROID_APP_ID'),
        messagingSenderId:
            _value(_messagingSenderId, 'FIREBASE_MESSAGING_SENDER_ID'),
        projectId: _value(_projectId, 'FIREBASE_PROJECT_ID'),
        storageBucket: _value(_storageBucket, 'FIREBASE_STORAGE_BUCKET'),
      );

  static FirebaseOptions get ios => FirebaseOptions(
        apiKey: _value(_iosApiKey, 'FIREBASE_IOS_API_KEY'),
        appId: _value(_iosAppId, 'FIREBASE_IOS_APP_ID'),
        messagingSenderId:
            _value(_messagingSenderId, 'FIREBASE_MESSAGING_SENDER_ID'),
        projectId: _value(_projectId, 'FIREBASE_PROJECT_ID'),
        storageBucket: _value(_storageBucket, 'FIREBASE_STORAGE_BUCKET'),
        iosBundleId: _value(_iosBundleId, 'FIREBASE_IOS_BUNDLE_ID'),
      );

  static FirebaseOptions get macos => FirebaseOptions(
        apiKey: _value(_iosApiKey, 'FIREBASE_IOS_API_KEY'),
        appId: _value(_iosAppId, 'FIREBASE_IOS_APP_ID'),
        messagingSenderId:
            _value(_messagingSenderId, 'FIREBASE_MESSAGING_SENDER_ID'),
        projectId: _value(_projectId, 'FIREBASE_PROJECT_ID'),
        storageBucket: _value(_storageBucket, 'FIREBASE_STORAGE_BUCKET'),
        iosBundleId: _value(_macosBundleId, 'FIREBASE_MACOS_BUNDLE_ID'),
      );

  static FirebaseOptions get windows => FirebaseOptions(
        apiKey: _value(_webApiKey, 'FIREBASE_WEB_API_KEY'),
        appId: _value(_webAppId, 'FIREBASE_WEB_APP_ID'),
        messagingSenderId:
            _value(_messagingSenderId, 'FIREBASE_MESSAGING_SENDER_ID'),
        projectId: _value(_projectId, 'FIREBASE_PROJECT_ID'),
        authDomain: _value(_authDomain, 'FIREBASE_AUTH_DOMAIN'),
        storageBucket: _value(_storageBucket, 'FIREBASE_STORAGE_BUCKET'),
        measurementId: _value(_measurementId, 'FIREBASE_MEASUREMENT_ID'),
      );

  static FirebaseOptions get linux => FirebaseOptions(
        apiKey: _value(_webApiKey, 'FIREBASE_WEB_API_KEY'),
        appId: _value(_webAppId, 'FIREBASE_WEB_APP_ID'),
        messagingSenderId:
            _value(_messagingSenderId, 'FIREBASE_MESSAGING_SENDER_ID'),
        projectId: _value(_projectId, 'FIREBASE_PROJECT_ID'),
        authDomain: _value(_authDomain, 'FIREBASE_AUTH_DOMAIN'),
        storageBucket: _value(_storageBucket, 'FIREBASE_STORAGE_BUCKET'),
        measurementId: _value(_measurementId, 'FIREBASE_MEASUREMENT_ID'),
      );
}
